### ISSUE TITLE
Stripping SCMS information doesn't work and causes errors?

### ISSUE THREAD

**Issue by avanada** [cybercase/webminidisc#110]
Stripping SCMS information doesn't seem to do anything and whenever I exit out of Homebrew mode, it gives me this error:

TypeError: E.setMode is not a function
    at B.updateFlagAllFragmentsOfTrack (https://web.minidisc.wiki/static/js/2.3287798a.chunk.js:2:8009790)
    at https://web.minidisc.wiki/static/js/main.aca23348.chunk.js:101:11072
    at https://web.minidisc.wiki/static/js/2.3287798a.chunk.js:2:165236
    at https://web.minidisc.wiki/static/js/main.aca23348.chunk.js:1:63330
    at https://web.minidisc.wiki/static/js/main.aca23348.chunk.js:101:10927
    at Object.w (https://web.minidisc.wiki/static/js/2.3287798a.chunk.js:2:1398335)
    at s (https://web.minidisc.wiki/static/js/2.3287798a.chunk.js:2:1398478)
    at https://web.minidisc.wiki/static/js/2.3287798a.chunk.js:2:1398624
    at c (https://web.minidisc.wiki/static/js/2.3287798a.chunk.js:2:1398710)
    at IB (https://web.minidisc.wiki/static/js/2.3287798a.chunk.js:2:1414313)

I use a Sony MZ-N505 Type-R. I'm not sure if I'm doing something wrong.

**Comment by asivery** [comment]
@avanada Hello, I'm sorry - at some point I mixed up two versions of my TOC editing library. It should be fixed in WMD Pro 1.3.2 - clear the cache, reload the page and you should be good to go :). Thanks for reporting the issue, and please let me know if it's resolved.

**Comment by avanada** [comment]
It works now. Thanks!
