### ISSUE TITLE
Feature request: transfer tracks to more than one connected MD device

### ISSUE THREAD

**Issue by cbmtrx** [cybercase/webminidisc#132]
Assuming the Mac/PC can be made to recognize multiple attached MD recorders, the same instructions could conceivably be communicated to each one—thereby allowing for faster duplication of MDs.

I'd imagine that some MD recorders could run a few seconds faster/slower than others, so the transfer process would likely complete after the last device had finished. The user would need to monitor their device statuses.

**Comment by asivery** [comment]
It's possible to open multiple instances of Web Minidisc in multiple windows / tabs. Wouldn't that be enough?

**Comment by cbmtrx** [comment]
I never even tried this! I just assumed that the browser would only recognize/transfer to a single USB device.

This will be the first thing I test in the morning.

**Comment by asivery** [comment]
Alright, please let me know how it goes :)
It would be possible to write a 'proxy' that duplicates every command to 2 devices, but it would be confusing, and workarounds would have to be made for things like progress bars.

**Comment by cbmtrx** [comment]
100% works. Got two running now and plan to test 3 simultaneously. Kind of amazing!

The Connect dialog simply shows all connected MD devices; had it open in 2 tabs, and picked one device for each.

I'll check payback but I'm assuming it's all good.

**Comment by cbmtrx** [comment]
I stand corrected: the second one did not in fact start. #1 and #3 were recording just fine. When I check the middle tab it had stopped with an "Unknown error"-type message. Then I began to get all kinds of weird problems. One, then the other tab stopped progressing, the MD players seemed to think they were connected but there was no connection. Progress bars frozen. Unplugging did not solve the problem, I'm assuming the browser didn't like the simultaneous writing (and unplugging etc) so this may not work with more than 2.

Will restart the computer and see if that clears out the junk.

--Restarted the browser, still getting weirdness.

The error message: "Error uploading to device. There might not be enough space left, or an unknown error occurred."

**Comment by cbmtrx** [comment]
Figured out what's happening. When I had 3 running, two were the same name in the device lineup. They are at different USB ports so I can only guess that the app is using the literal name as the device identifier (?). When I tried just two devices of the same name, same problems. When I switched back to two different devices, no more problems.

So, just a naming/port thing?

**Comment by cbmtrx** [comment]
Error detail:

`TypeError: Cannot read properties of null (reading 'groups')
    at l (https://web.minidisc.wiki/static/js/2.83f0643a.chunk.js:2:2222112)
    at https://web.minidisc.wiki/static/js/main.dcf6f445.chunk.js:1:75758
    at async https://web.minidisc.wiki/static/js/main.dcf6f445.chunk.js:1:63132`

**Comment by cbmtrx** [comment]
So yeah, all is not as it first seemed. It seemed to work **the very first time** and after that it has just not been well-behaved, a little glitchy and I've never succeed in getting two to run simultaneously again. One will start, the other will start then immediately fail. If you unhook the failed one, the first one also disconnects. One device always seems to be solid, whereas the others (I've tried switching out 2) are now always failing.

**Comment by cbmtrx** [comment]
And get this: When I moved one of the devices where recording had failed and hooked it up to a different computer, **it failed there also**. These are new MDs. I had noticed this weirdness before and was using either the wipe function or my Sony deck to erase all but evidently webminidiscpro is somehow corrupting the TOC on the MDs themselves. When I inserted a different MD over at the new computer it worked fine.

I encountered this before and had been putting those "problem MDs" from the "failed" device (NE410) into the working device (N420D), which had no problem.

I don't know enough about how this works to understand what's going on but it seems like multi-setups run the risk of corrupting the disks themselves. Hmm.

**Comment by cbmtrx** [comment]
I learn more every day: seems to have nothing to do with the name/model of the device as I'm now successfully using 2 very similar models. My working theory is that the other device was Hi-MD and that was somehow screwing stuff up.

I love this app.

**Comment by asivery** [comment]
@cbmtrx I don't think the other device being HiMD-capable might have caused this problem. I'll investigate on my hardware.
