### ISSUE TITLE
Build error

### ISSUE THREAD

**Issue by ookris** [cybercase/webminidisc#33]
After running the npm start command, the console shows such errors:

```
ookris@webminidisc:~/webminidisc$ npm build
npm WARN build `npm build` called with no arguments. Did you mean to `npm run-script build`?
ookris@webminidisc:~/webminidisc$ npm run-script build

> webmd@0.1.0 build /home/ookris/webminidisc
> react-scripts build && cat public/extra-service-worker.js build/service-worker.js > build/final-service-worker.js

Creating an optimized production build...
Browserslist: caniuse-lite is outdated. Please run the following command: `yarn upgrade`

<--- Last few GCs --->

[18821:0x3ac7e20]   209171 ms: Scavenge 485.6 (492.8) -> 485.2 (493.0) MB, 5.8 / 0.0 ms  (average mu = 0.163, current mu = 0.011) allocation failure 
[18821:0x3ac7e20]   209178 ms: Scavenge 485.9 (493.0) -> 485.4 (493.5) MB, 4.5 / 0.0 ms  (average mu = 0.163, current mu = 0.011) allocation failure 
[18821:0x3ac7e20]   210006 ms: Mark-sweep 486.2 (493.5) -> 482.6 (493.5) MB, 825.0 / 0.0 ms  (average mu = 0.165, current mu = 0.167) allocation failure scavenge might not succeed


<--- JS stacktrace --->

==== JS stack trace =========================================

    0: ExitFrame [pc: 0x140a859]
    1: StubFrame [pc: 0x13eb1bb]
Security context: 0x1005957008d1 <JSObject>
    2: split [0x10059570cd51](this=0x0a215e4f2029 <String[95]: /home/ookris/webminidisc/node_modules/@material-ui/lab/esm/ToggleButtonGroup/isValueSelected.js>,0x0a215e4f4dc1 <JSRegExp <String[#3]: \/+>>)
    3: normalize [0xefcd8bde521] [/home/ookris/webminidisc/node_modules/source-map/lib/util.js:~80] [pc=0x3d047960b1da](this=0x...

FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory
 1: 0xa18150 node::Abort() [node]
 2: 0xa1855c node::OnFatalError(char const*, char const*) [node]
 3: 0xb970be v8::Utils::ReportOOMFailure(v8::internal::Isolate*, char const*, bool) [node]
 4: 0xb97439 v8::internal::V8::FatalProcessOutOfMemory(v8::internal::Isolate*, char const*, bool) [node]
 5: 0xd546b5  [node]
 6: 0xd54d46 v8::internal::Heap::RecomputeLimits(v8::internal::GarbageCollector) [node]
 7: 0xd61605 v8::internal::Heap::PerformGarbageCollection(v8::internal::GarbageCollector, v8::GCCallbackFlags) [node]
 8: 0xd624b5 v8::internal::Heap::CollectGarbage(v8::internal::AllocationSpace, v8::internal::GarbageCollectionReason, v8::GCCallbackFlags) [node]
 9: 0xd64f6c v8::internal::Heap::AllocateRawWithRetryOrFail(int, v8::internal::AllocationType, v8::internal::AllocationOrigin, v8::internal::AllocationAlignment) [node]
10: 0xd2b98b v8::internal::Factory::NewFillerObject(int, bool, v8::internal::AllocationType, v8::internal::AllocationOrigin) [node]
11: 0x106df5e v8::internal::Runtime_AllocateInYoungGeneration(int, unsigned long*, v8::internal::Isolate*) [node]
12: 0x140a859  [node]
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! webmd@0.1.0 build: `react-scripts build && cat public/extra-service-worker.js build/service-worker.js > build/final-service-worker.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the webmd@0.1.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/ookris/.npm/_logs/2021-02-13T19_51_50_242Z-debug.log
```

**2021-02-13T19_51_50_242Z-debug.log**

```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'run-script', 'build' ]
2 info using npm@6.14.11
3 info using node@v12.20.2
4 verbose run-script [ 'prebuild', 'build', 'postbuild' ]
5 info lifecycle webmd@0.1.0~prebuild: webmd@0.1.0
6 info lifecycle webmd@0.1.0~build: webmd@0.1.0
7 verbose lifecycle webmd@0.1.0~build: unsafe-perm in lifecycle true
8 verbose lifecycle webmd@0.1.0~build: PATH: /usr/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/home/ookris/webminidisc/node_modules/.bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
9 verbose lifecycle webmd@0.1.0~build: CWD: /home/ookris/webminidisc
10 silly lifecycle webmd@0.1.0~build: Args: [
10 silly lifecycle   '-c',
10 silly lifecycle   'react-scripts build && cat public/extra-service-worker.js build/service-worker.js > build/final-service-worker.js'
10 silly lifecycle ]
11 silly lifecycle webmd@0.1.0~build: Returned: code: 1  signal: null
12 info lifecycle webmd@0.1.0~build: Failed to exec build script
13 verbose stack Error: webmd@0.1.0 build: `react-scripts build && cat public/extra-service-worker.js build/service-worker.js > build/final-service-worker.js`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:314:20)
13 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:314:20)
13 verbose stack     at maybeClose (internal/child_process.js:1022:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:287:5)
14 verbose pkgid webmd@0.1.0
15 verbose cwd /home/ookris/webminidisc
16 verbose Linux 4.15.0-135-generic
17 verbose argv "/usr/bin/node" "/usr/bin/npm" "run-script" "build"
18 verbose node v12.20.2
19 verbose npm  v6.14.11
20 error code ELIFECYCLE
21 error errno 1
22 error webmd@0.1.0 build: `react-scripts build && cat public/extra-service-worker.js build/service-worker.js > build/final-service-worker.js`
22 error Exit status 1
23 error Failed at the webmd@0.1.0 build script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]

```

**Comment by cybercase** [comment]
That `FatalProcessOutOfMemory` might be a hint that the issue is not related to the project itself, but more likely to the environment.

**Comment by cybercase** [comment]
You could also try something like this: https://stackoverflow.com/questions/53230823/fatal-error-ineffective-mark-compacts-near-heap-limit-allocation-failed-javas
